//! Generated by zuc (zumar-lang). Do not edit; edit the .zu source.
#![allow(unused_variables, unused_parens, unused_braces, clippy::all)]

use wasm_bindgen::prelude::*;
use zumar_core::{el, text, VNode};
use zumar_runtime::{effects::Cmds, Program};

#[derive(Clone)]
pub struct Item {
    pub id: i64,
    pub text: String,
    pub done: bool,
}

#[derive(Clone)]
pub enum Msg {
    Draft(String),
    Add,
    Toggle(i64),
    Delete(i64),
    Reverse,
}

pub struct Model {
    pub draft: String,
    pub items: Vec<Item>,
    pub seq: i64,
}

fn init_model() -> Model {
    Model {
        draft: "".to_string(),
        items: Vec::new(),
        seq: 1i64,
    }
}

fn update(model: &mut Model, msg: Msg) -> Cmds<Msg> {
    match msg {
        Msg::Draft(s) => {
            let __new_draft: String = s.clone();
            model.draft = __new_draft;
        }
        Msg::Add => {
            let __new_items: Vec<Item> = { let mut __v0 = model.items.clone(); __v0.extend(vec![Item { id: model.seq, text: model.draft.clone(), done: false }]); __v0 };
            let __new_seq: i64 = (model.seq + 1i64);
            let __new_draft: String = "".to_string();
            model.items = __new_items;
            model.seq = __new_seq;
            model.draft = __new_draft;
        }
        Msg::Toggle(id) => {
            let __new_items: Vec<Item> = { let mut __acc1: Vec<Item> = Vec::new(); for t in (model.items.clone()).iter() { __acc1.push((if (t.id == id) { Item { done: (!t.done), ..t.clone() } } else { t.clone() })); } __acc1 };
            model.items = __new_items;
        }
        Msg::Delete(id) => {
            let __new_items: Vec<Item> = { let mut __acc2: Vec<Item> = Vec::new(); for t in (model.items.clone()).iter() { if (t.id != id) { __acc2.push(t.clone()); } } __acc2 };
            model.items = __new_items;
        }
        Msg::Reverse => {
            let __new_items: Vec<Item> = { let mut __v3 = model.items.clone(); __v3.reverse(); __v3 };
            model.items = __new_items;
        }
    }
    Vec::new()
}

fn view(model: &Model) -> VNode<Msg> {
    let __root = el("div").attr("class", "todo".to_string()).child(el("h1").child(text("zumar todo".to_string()))).child(el("p").attr("class", "sub".to_string()).child(text("compiled from todo.zu".to_string()))).child(el("form").on_submit(Msg::Add).child(el("input").attr("type", "text".to_string()).attr("placeholder", "what needs doing?".to_string()).attr("value", model.draft.clone()).on_input(Msg::Draft)).child(el("button").attr("type", "submit".to_string()).child(text("add".to_string())))).child(el("div").attr("class", "bar".to_string()).child(el("span").child(text(format!("{}{}", ((({ let mut __acc4: Vec<Item> = Vec::new(); for t in (model.items.clone()).iter() { if (!t.done) { __acc4.push(t.clone()); } } __acc4 }).len() as i64)).to_string(), " open".to_string())))).child(el("button").on("click", Msg::Reverse).child(text("reverse".to_string())))).child({
        let mut __el5 = el("ul").attr("class", "items".to_string());
        for t in (model.items.clone()).iter() { __el5 = __el5.child(el("li").key((t.id).to_string()).attr("class", (if t.done { "done".to_string() } else { "open".to_string() })).child(el("span").attr("class", "check".to_string()).on("click", Msg::Toggle(t.id)).child(text((if t.done { "[x]".to_string() } else { "[ ]".to_string() })))).child(el("span").attr("class", "label".to_string()).child(text(t.text.clone()))).child(el("button").attr("class", "del".to_string()).on("click", Msg::Delete(t.id)).child(text("x".to_string())))); }
        __el5
    });
    VNode::from(__root)
}

zumar_runtime::zumar_app!(App, Model, Msg, Program::new(init_model(), update, view));
