//! Backend: emit a Rust crate that drives the zumar TEA runtime directly.
//! The generated crate is indistinguishable from a hand-written example —
//! same builders, same `zumar_app!` wrapper, same wire protocol. A WasmGC
//! backend replaces this module later behind the same AST.
//!
//! Expressions are emitted bottom-up as `(code, type)` pairs so the emitter
//! knows when a value must be cloned (owned String/List/record out of a
//! borrowed place) versus copied (Int/Bool).

use std::cell::Cell;
use std::collections::BTreeMap;

use crate::ast::*;

pub struct Generated {
    pub crate_name: String,
    pub cargo_toml: String,
    pub lib_rs: String,
}

/// `deps` is the `[dependencies]` fragment wiring zumar-core / zumar-runtime
/// (path, git, or version) — see zuc for how it's chosen.
pub fn generate(app: &App, deps: &str) -> Generated {
    let crate_name = app.name.to_lowercase();
    let g = Gen::new(app);
    Generated {
        cargo_toml: cargo_toml(&crate_name, deps),
        lib_rs: g.lib_rs(app),
        crate_name,
    }
}

fn cargo_toml(name: &str, deps: &str) -> String {
    format!(
        r#"[package]
name = "{name}"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
{deps}
wasm-bindgen = "0.2"

[workspace]
"#
    )
}

type Env = Vec<(String, Ty)>;

struct Gen {
    records: BTreeMap<String, Vec<(String, Ty)>>,
    enums: BTreeMap<String, Vec<(String, Option<Ty>)>>,
    /// Constructor -> owning enum.
    variant_owner: BTreeMap<String, String>,
    next: Cell<usize>,
}

impl Gen {
    fn new(app: &App) -> Gen {
        let mut records = BTreeMap::new();
        for r in &app.records {
            records.insert(
                r.name.clone(),
                r.fields
                    .iter()
                    .map(|(n, t, _)| (n.clone(), t.clone()))
                    .collect(),
            );
        }
        records.insert(
            MODEL.into(),
            app.model
                .iter()
                .map(|(n, t, _)| (n.clone(), t.clone()))
                .collect(),
        );
        let mut enums = BTreeMap::new();
        let mut variant_owner = BTreeMap::new();
        for e in &app.enums {
            for (v, _, _) in &e.variants {
                variant_owner.insert(v.clone(), e.name.clone());
            }
            enums.insert(
                e.name.clone(),
                e.variants
                    .iter()
                    .map(|(v, p, _)| (v.clone(), p.clone()))
                    .collect(),
            );
        }
        Gen {
            records,
            enums,
            variant_owner,
            next: Cell::new(0),
        }
    }

    fn fresh(&self) -> usize {
        let n = self.next.get();
        self.next.set(n + 1);
        n
    }

    fn field_ty(&self, record: &str, field: &str) -> Ty {
        self.records[record]
            .iter()
            .find(|(n, _)| n == field)
            .map(|(_, t)| t.clone())
            .expect("typechecked: field exists")
    }

    fn lib_rs(&self, app: &App) -> String {
        let mut o = String::new();
        o.push_str("//! Generated by zuc (zumar-lang). Do not edit; edit the .zu source.\n");
        o.push_str("#![allow(unused_variables, unused_parens, unused_braces, clippy::all)]\n\n");
        o.push_str("use wasm_bindgen::prelude::*;\n");
        o.push_str("use zumar_core::{el, text, VNode};\n");
        o.push_str("use zumar_runtime::{effects::Cmds, Program};\n\n");

        // Records.
        for r in &app.records {
            o.push_str("#[derive(Clone)]\npub struct ");
            o.push_str(&r.name);
            o.push_str(" {\n");
            for (n, t, _) in &r.fields {
                o.push_str(&format!("    pub {n}: {},\n", rust_ty(t)));
            }
            o.push_str("}\n\n");
        }

        // Enums.
        for e in &app.enums {
            o.push_str("#[derive(Clone, PartialEq)]\npub enum ");
            o.push_str(&e.name);
            o.push_str(" {\n");
            for (v, payload, _) in &e.variants {
                match payload {
                    Some(t) => o.push_str(&format!("    {v}({}),\n", rust_ty(t))),
                    None => o.push_str(&format!("    {v},\n")),
                }
            }
            o.push_str("}\n\n");
        }

        // Msg.
        o.push_str("#[derive(Clone)]\npub enum Msg {\n");
        for m in &app.msgs {
            match &m.payload {
                Some(t) => o.push_str(&format!("    {}({}),\n", m.name, rust_ty(t))),
                None => o.push_str(&format!("    {},\n", m.name)),
            }
        }
        o.push_str("}\n\n");

        // Model.
        o.push_str("pub struct Model {\n");
        for (n, t, _) in &app.model {
            o.push_str(&format!("    pub {n}: {},\n", rust_ty(t)));
        }
        o.push_str("}\n\n");

        // init.
        o.push_str("fn init_model() -> Model {\n    Model {\n");
        for (name, expr, _) in &app.init {
            let want = self.field_ty(MODEL, name);
            let (code, _) = self.emit(expr, Some(&want), &Env::new());
            o.push_str(&format!("        {name}: {code},\n"));
        }
        o.push_str("    }\n}\n\n");

        // update — evaluate every new field against the pre-update model,
        // then assign (record-update semantics).
        o.push_str("fn update(model: &mut Model, msg: Msg) -> Cmds<Msg> {\n    match msg {\n");
        for u in &app.updates {
            let mut env: Env = vec![("model".into(), Ty::Record(MODEL.into()))];
            let pat = match &u.var {
                Some((v, _)) => {
                    // Recover the payload type from the msg for the env.
                    if let Some(m) = app.msgs.iter().find(|m| m.name == u.msg) {
                        if let Some(t) = &m.payload {
                            env.push((v.clone(), t.clone()));
                        }
                    }
                    format!("Msg::{}({})", u.msg, v)
                }
                None => format!("Msg::{}", u.msg),
            };
            o.push_str(&format!("        {pat} => {{\n"));
            for (name, expr, _) in &u.fields {
                let want = self.field_ty(MODEL, name);
                let (code, _) = self.emit(expr, Some(&want), &env);
                o.push_str(&format!(
                    "            let __new_{name}: {} = {code};\n",
                    rust_ty(&want)
                ));
            }
            for (name, _, _) in &u.fields {
                o.push_str(&format!("            model.{name} = __new_{name};\n"));
            }
            if !u.cmds.is_empty() {
                o.push_str(&format!(
                    "            return vec![{}];\n",
                    self.emit_cmds(&u.cmds, &env)
                ));
            }
            o.push_str("        }\n");
        }
        o.push_str("    }\n    Vec::new()\n}\n\n");

        // Effect callbacks: one named fn per httpGet ctor and per clocked
        // `every` ctor (the runtime takes fn pointers, not closures).
        for ctor in self.http_ctors(app) {
            o.push_str(&format!(
                "fn __http_{lc}(r: zumar_runtime::effects::HttpResult) -> Msg {{\n    Msg::{ctor}(if r.ok {{ r.body }} else {{ format!(\"error {{}}\", r.status) }})\n}}\n\n",
                lc = ctor.to_lowercase(),
            ));
        }
        for ctor in self.clocked_sub_ctors(app) {
            o.push_str(&format!(
                "fn __tick_{lc}(now: f64) -> Msg {{\n    Msg::{ctor}(now as i64)\n}}\n\n",
                lc = ctor.to_lowercase(),
            ));
        }

        // subs.
        if let Some(subs) = &app.subs {
            let env: Env = vec![("model".into(), Ty::Record(MODEL.into()))];
            o.push_str(
                "#[allow(unused_variables)]\nfn subs(model: &Model) -> Vec<zumar_runtime::effects::Sub<Msg>> {\n    ",
            );
            o.push_str(&self.emit_subs(subs, app, &env));
            o.push_str("\n}\n\n");
        }

        // view.
        o.push_str("fn view(model: &Model) -> VNode<Msg> {\n");
        let env: Env = vec![("model".into(), Ty::Record(MODEL.into()))];
        let root = self.emit_element(&app.view, &env);
        o.push_str(&format!(
            "    let __root = {root};\n    VNode::from(__root)\n}}\n\n"
        ));

        let mut program = String::from("Program::new(init_model(), update, view)");
        if app.subs.is_some() {
            program.push_str(".with_subscriptions(subs)");
        }
        if !app.init_cmds.is_empty() {
            program.push_str(&format!(
                ".with_init(vec![{}])",
                self.emit_cmds(&app.init_cmds, &Env::new())
            ));
        }
        o.push_str(&format!(
            "zumar_runtime::zumar_app!(App, Model, Msg, {program});\n"
        ));
        o
    }

    fn http_ctors(&self, app: &App) -> Vec<String> {
        let mut ctors: Vec<String> = Vec::new();
        let all = app
            .init_cmds
            .iter()
            .chain(app.updates.iter().flat_map(|u| u.cmds.iter()));
        for cmd in all {
            if let CmdCall::HttpGet { ctor, .. } = cmd {
                if !ctors.contains(ctor) {
                    ctors.push(ctor.clone());
                }
            }
        }
        ctors
    }

    fn clocked_sub_ctors(&self, app: &App) -> Vec<String> {
        let mut ctors = Vec::new();
        fn walk(subs: &SubExpr, app: &App, out: &mut Vec<String>) {
            match subs {
                SubExpr::List(calls) => {
                    for c in calls {
                        let clocked = app
                            .msgs
                            .iter()
                            .any(|m| m.name == c.msg && m.payload.is_some());
                        if clocked && !out.contains(&c.msg) {
                            out.push(c.msg.clone());
                        }
                    }
                }
                SubExpr::If(_, t, f, _) => {
                    walk(t, app, out);
                    walk(f, app, out);
                }
            }
        }
        if let Some(subs) = &app.subs {
            walk(subs, app, &mut ctors);
        }
        ctors
    }

    fn emit_cmds(&self, cmds: &[CmdCall], env: &Env) -> String {
        cmds.iter()
            .map(|cmd| match cmd {
                CmdCall::Delay { ms, msg, .. } => {
                    format!("zumar_runtime::delay({ms}, Msg::{msg})")
                }
                CmdCall::HttpGet { url, ctor, .. } => {
                    let (code, _) = self.emit(url, Some(&Ty::Str), env);
                    format!(
                        "zumar_runtime::http_get({code}, __http_{})",
                        ctor.to_lowercase()
                    )
                }
            })
            .collect::<Vec<_>>()
            .join(", ")
    }

    fn emit_subs(&self, subs: &SubExpr, app: &App, env: &Env) -> String {
        match subs {
            SubExpr::List(calls) => {
                let items: Vec<String> = calls
                    .iter()
                    .map(|c| {
                        let clocked = app
                            .msgs
                            .iter()
                            .any(|m| m.name == c.msg && m.payload.is_some());
                        if clocked {
                            format!(
                                "zumar_runtime::every_with_now({}, __tick_{})",
                                c.ms,
                                c.msg.to_lowercase()
                            )
                        } else {
                            format!("zumar_runtime::every({}, Msg::{})", c.ms, c.msg)
                        }
                    })
                    .collect();
                format!("vec![{}]", items.join(", "))
            }
            SubExpr::If(cond, t, f, _) => {
                let (cc, _) = self.emit(cond, Some(&Ty::Bool), env);
                format!(
                    "(if {cc} {{ {} }} else {{ {} }})",
                    self.emit_subs(t, app, env),
                    self.emit_subs(f, app, env)
                )
            }
        }
    }

    // --- view ------------------------------------------------------------

    fn emit_element(&self, el: &Element, env: &Env) -> String {
        let attrs = self.emit_attrs(el, env);
        let has_for = el.children.iter().any(|c| matches!(c, Child::For { .. }));

        if !has_for {
            let mut s = format!("el(\"{}\"){attrs}", esc(&el.tag));
            for child in &el.children {
                s.push_str(&format!(".child({})", self.emit_child(child, env)));
            }
            return s;
        }

        let d = self.fresh();
        let mut s = format!(
            "{{\n        let mut __el{d} = el(\"{}\"){attrs};\n",
            esc(&el.tag)
        );
        for child in &el.children {
            match child {
                Child::For {
                    var, list, body, ..
                } => {
                    let (src, _) = self.emit(list, None, env);
                    let mut inner = env.clone();
                    let elem = self.list_elem(list, env);
                    inner.push((var.clone(), elem));
                    let body_code = self.emit_element(body, &inner);
                    s.push_str(&format!(
                        "        for {var} in ({src}).iter() {{ __el{d} = __el{d}.child({body_code}); }}\n"
                    ));
                }
                other => {
                    s.push_str(&format!(
                        "        __el{d} = __el{d}.child({});\n",
                        self.emit_child(other, env)
                    ));
                }
            }
        }
        s.push_str(&format!("        __el{d}\n    }}"));
        s
    }

    fn emit_child(&self, child: &Child, env: &Env) -> String {
        match child {
            Child::Elem(e) => self.emit_element(e, env),
            Child::Text(expr, _) => {
                let (code, _) = self.emit(expr, Some(&Ty::Str), env);
                format!("text({code})")
            }
            Child::For { .. } => unreachable!("for-children handled in emit_element"),
        }
    }

    fn emit_attrs(&self, el: &Element, env: &Env) -> String {
        let mut s = String::new();
        for attr in &el.attrs {
            match attr {
                Attr::Str { name, value, .. } if name == "key" => {
                    let (code, _) = self.emit(value, Some(&Ty::Str), env);
                    s.push_str(&format!(".key({code})"));
                }
                Attr::Str { name, value, .. } => {
                    let (code, _) = self.emit(value, Some(&Ty::Str), env);
                    s.push_str(&format!(".attr(\"{}\", {code})", esc(name)));
                }
                Attr::On {
                    event,
                    handler,
                    prevent_default,
                } => {
                    let msg = self.emit_msg_call(handler, env);
                    if *prevent_default {
                        s.push_str(&format!(".on_submit({msg})"));
                    } else {
                        s.push_str(&format!(".on(\"{}\", {msg})", esc(event)));
                    }
                }
                Attr::OnValue { kind, ctor, .. } => match kind {
                    ValueKind::Value => s.push_str(&format!(".on_input(Msg::{ctor})")),
                    ValueKind::Checked => s.push_str(&format!(".on_check(Msg::{ctor})")),
                },
            }
        }
        s
    }

    fn emit_msg_call(&self, call: &MsgCall, env: &Env) -> String {
        match &call.arg {
            Some(arg) => {
                let (code, _) = self.emit(arg, None, env);
                format!("Msg::{}({code})", call.name)
            }
            None => format!("Msg::{}", call.name),
        }
    }

    // --- expressions -----------------------------------------------------

    fn list_elem(&self, list: &Expr, env: &Env) -> Ty {
        match self.type_of(list, env) {
            Ty::List(t) => *t,
            _ => unreachable!("typechecked: list"),
        }
    }

    /// Emit an owned value plus its type. `expected` disambiguates empty
    /// lists and record literals.
    fn emit(&self, expr: &Expr, expected: Option<&Ty>, env: &Env) -> (String, Ty) {
        match expr {
            Expr::Int(n) => (format!("{n}i64"), Ty::Int),
            Expr::Bool(b) => (format!("{b}"), Ty::Bool),
            Expr::Str(s) => (format!("\"{}\".to_string()", esc(s)), Ty::Str),
            Expr::Var(name, _) => {
                if let Some((_, t)) = env.iter().rev().find(|(n, _)| n == name) {
                    let ty = t.clone();
                    return (clone_if_owned(name, &ty), ty);
                }
                let owner = self.variant_owner[name].clone();
                (format!("{owner}::{name}"), Ty::Enum(owner))
            }
            Expr::Ctor(name, arg, _) => {
                let owner = self.variant_owner[name].clone();
                let payload = self.enums[&owner]
                    .iter()
                    .find(|(v, _)| v == name)
                    .and_then(|(_, p)| p.clone())
                    .expect("typechecked: ctor has payload");
                let (code, _) = self.emit(arg, Some(&payload), env);
                (format!("{owner}::{name}({code})"), Ty::Enum(owner))
            }
            Expr::Field(base, field, _) => {
                let (place, bty) = self.emit_place(base, env);
                let rec = match bty {
                    Ty::Record(r) => r,
                    _ => unreachable!("typechecked: record base"),
                };
                let ft = self.field_ty(&rec, field);
                let code = format!("{place}.{field}");
                (clone_if_owned(&code, &ft), ft)
            }
            Expr::Show(inner, _) => {
                let (code, _) = self.emit(inner, Some(&Ty::Int), env);
                (format!("({code}).to_string()"), Ty::Str)
            }
            Expr::Len(inner, _) => {
                let code = self.emit_operand(inner, env);
                (format!("(({code}).len() as i64)"), Ty::Int)
            }
            Expr::Sum(inner, _) => {
                let code = self.emit_operand(inner, env);
                (format!("(({code}).iter().sum::<i64>())"), Ty::Int)
            }
            Expr::ToInt(inner, _) => {
                let code = self.emit_operand(inner, env);
                (format!("({code}.parse::<i64>().unwrap_or(0))"), Ty::Int)
            }
            Expr::Nth(list, index, default, _) => {
                let list_code = self.emit_operand(list, env);
                let elem = match self.type_of(list, env) {
                    Ty::List(t) => *t,
                    _ => unreachable!("typechecked: list"),
                };
                let (idx, _) = self.emit(index, Some(&Ty::Int), env);
                let (def, _) = self.emit(default, Some(&elem), env);
                (
                    format!("({list_code}.get(({idx}) as usize).cloned().unwrap_or({def}))"),
                    elem,
                )
            }
            Expr::Head(list, _) => {
                let list_code = self.emit_operand(list, env);
                let elem = match self.type_of(list, env) {
                    Ty::List(t) => *t,
                    _ => unreachable!("typechecked: list"),
                };
                (
                    format!("({list_code}.first().cloned())"),
                    Ty::Maybe(Box::new(elem)),
                )
            }
            Expr::None(_) => {
                let ty = expected.cloned().expect("typechecked: none has a hint");
                ("None".to_string(), ty)
            }
            Expr::Some(inner, _) => {
                let hint = match expected {
                    Some(Ty::Maybe(t)) => Some(t.as_ref().clone()),
                    _ => None,
                };
                let (code, ty) = self.emit(inner, hint.as_ref(), env);
                (format!("Some({code})"), Ty::Maybe(Box::new(ty)))
            }
            Expr::Case { scrut, arms, .. } => {
                let (sc, scrut_ty) = self.emit(scrut, None, env);
                let mut parts = Vec::new();
                let mut body_ty = Ty::Int;
                for arm in arms {
                    let (pattern, arm_env) = match &scrut_ty {
                        Ty::Maybe(inner) => match arm.ctor.as_str() {
                            "none" => ("None".to_string(), env.clone()),
                            _ => {
                                let b = arm.binder.clone().unwrap();
                                let mut e = env.clone();
                                e.push((b.clone(), inner.as_ref().clone()));
                                (format!("Some({b})"), e)
                            }
                        },
                        Ty::Enum(en) => {
                            let payload = self.enums[en]
                                .iter()
                                .find(|(v, _)| *v == arm.ctor)
                                .and_then(|(_, p)| p.clone());
                            match (&arm.binder, payload) {
                                (Some(b), Some(pt)) => {
                                    let mut e = env.clone();
                                    e.push((b.clone(), pt));
                                    (format!("{en}::{}({b})", arm.ctor), e)
                                }
                                _ => (format!("{en}::{}", arm.ctor), env.clone()),
                            }
                        }
                        _ => unreachable!("typechecked: case scrutinee"),
                    };
                    let (body, ty) = self.emit(&arm.body, expected, &arm_env);
                    body_ty = ty;
                    parts.push(format!("{pattern} => {{ {body} }}"));
                }
                (format!("(match {sc} {{ {} }})", parts.join(" ")), body_ty)
            }
            Expr::Reverse(inner, _) => {
                let (code, ty) = self.emit(inner, expected, env);
                let d = self.fresh();
                (
                    format!("{{ let mut __v{d} = {code}; __v{d}.reverse(); __v{d} }}"),
                    ty,
                )
            }
            Expr::Not(inner, _) => {
                let (code, _) = self.emit(inner, Some(&Ty::Bool), env);
                (format!("(!{code})"), Ty::Bool)
            }
            Expr::Bin(op, l, r, _) => self.emit_bin(*op, l, r, env),
            Expr::If(c, t, e, _) => {
                let (cc, _) = self.emit(c, Some(&Ty::Bool), env);
                let (tc, ty) = self.emit(t, expected, env);
                let (ec, _) = self.emit(e, expected, env);
                (format!("(if {cc} {{ {tc} }} else {{ {ec} }})"), ty)
            }
            Expr::ListLit(items, _) => {
                let elem_hint = match expected {
                    Some(Ty::List(t)) => Some(t.as_ref().clone()),
                    _ => None,
                };
                if items.is_empty() {
                    let ty = elem_hint.expect("typechecked: empty list has a hint");
                    return ("Vec::new()".into(), Ty::List(Box::new(ty)));
                }
                let mut parts = Vec::new();
                let mut elem_ty = None;
                for it in items {
                    let (code, ty) = self.emit(it, elem_hint.as_ref(), env);
                    parts.push(code);
                    elem_ty = Some(ty);
                }
                (
                    format!("vec![{}]", parts.join(", ")),
                    Ty::List(Box::new(elem_ty.unwrap())),
                )
            }
            Expr::RecordLit(fields, _) => {
                let name = self.resolve_record(fields, expected);
                let body = self.emit_record_fields(&name, fields, env);
                (format!("{name} {{ {body} }}"), Ty::Record(name))
            }
            Expr::RecordUpdate(base, fields, _) => {
                let (base_code, bty) = self.emit(base, expected, env);
                let name = match &bty {
                    Ty::Record(r) => r.clone(),
                    _ => unreachable!("typechecked: record base"),
                };
                let body = self.emit_record_fields(&name, fields, env);
                (format!("{name} {{ {body}, ..{base_code} }}"), bty)
            }
            Expr::For {
                var,
                list,
                cond,
                body,
                ..
            } => {
                let (src, _) = self.emit(list, None, env);
                let mut inner = env.clone();
                let elem = self.list_elem(list, env);
                inner.push((var.clone(), elem));
                let body_hint = match expected {
                    Some(Ty::List(t)) => Some(t.as_ref().clone()),
                    _ => None,
                };
                let (body_code, body_ty) = self.emit(body, body_hint.as_ref(), &inner);
                let d = self.fresh();
                let push = match cond {
                    Some(c) => {
                        let (cc, _) = self.emit(c, Some(&Ty::Bool), &inner);
                        format!("if {cc} {{ __acc{d}.push({body_code}); }}")
                    }
                    None => format!("__acc{d}.push({body_code});"),
                };
                let code = format!(
                    "{{ let mut __acc{d}: Vec<{}> = Vec::new(); for {var} in ({src}).iter() {{ {push} }} __acc{d} }}",
                    rust_ty(&body_ty)
                );
                (code, Ty::List(Box::new(body_ty)))
            }
        }
    }

    fn emit_bin(&self, op: Op, l: &Expr, r: &Expr, env: &Env) -> (String, Ty) {
        match op {
            Op::Add | Op::Sub | Op::Mul => {
                let (a, _) = self.emit(l, Some(&Ty::Int), env);
                let (b, _) = self.emit(r, Some(&Ty::Int), env);
                let sym = match op {
                    Op::Add => "+",
                    Op::Sub => "-",
                    _ => "*",
                };
                (format!("({a} {sym} {b})"), Ty::Int)
            }
            // Division/remainder by zero yield 0 (Elm's rule) — no panics.
            Op::Div | Op::Rem => {
                let (a, _) = self.emit(l, Some(&Ty::Int), env);
                let (b, _) = self.emit(r, Some(&Ty::Int), env);
                let method = if op == Op::Div {
                    "checked_div"
                } else {
                    "checked_rem"
                };
                (format!("(({a}).{method}({b}).unwrap_or(0))"), Ty::Int)
            }
            Op::Concat => {
                let (a, at) = self.emit(l, None, env);
                let (b, _) = self.emit(r, None, env);
                match at {
                    Ty::Str => (format!("format!(\"{{}}{{}}\", {a}, {b})"), Ty::Str),
                    Ty::List(_) => {
                        let d = self.fresh();
                        (
                            format!("{{ let mut __v{d} = {a}; __v{d}.extend({b}); __v{d} }}"),
                            at,
                        )
                    }
                    _ => unreachable!("typechecked: ++ operands"),
                }
            }
            Op::Eq | Op::Ne | Op::Lt | Op::Gt => {
                let (a, _) = self.emit(l, None, env);
                let (b, _) = self.emit(r, None, env);
                let sym = match op {
                    Op::Eq => "==",
                    Op::Ne => "!=",
                    Op::Lt => "<",
                    _ => ">",
                };
                (format!("({a} {sym} {b})"), Ty::Bool)
            }
        }
    }

    /// A borrow-friendly operand for builtins whose method call auto-refs
    /// (`.len()`/`.iter()`/`.get()`/`.parse()`): a place stays a place (no
    /// clone), anything else is emitted owned.
    fn emit_operand(&self, expr: &Expr, env: &Env) -> String {
        match expr {
            Expr::Var(..) | Expr::Field(..) => self.emit_place(expr, env).0,
            _ => self.emit(expr, None, env).0,
        }
    }

    /// A borrow path (no clone) for a Var/Field chain — used as the base of a
    /// field access and other places.
    fn emit_place(&self, expr: &Expr, env: &Env) -> (String, Ty) {
        match expr {
            Expr::Var(name, _) => (name.clone(), self.lookup(name, env)),
            Expr::Field(base, field, _) => {
                let (place, bty) = self.emit_place(base, env);
                let rec = match bty {
                    Ty::Record(r) => r,
                    _ => unreachable!("typechecked: record base"),
                };
                let ft = self.field_ty(&rec, field);
                (format!("{place}.{field}"), ft)
            }
            other => {
                let (code, ty) = self.emit(other, None, env);
                (format!("({code})"), ty)
            }
        }
    }

    fn emit_record_fields(&self, name: &str, fields: &Record, env: &Env) -> String {
        let mut parts = Vec::new();
        for (fname, fexpr, _) in fields {
            let want = self.field_ty(name, fname);
            let (code, _) = self.emit(fexpr, Some(&want), env);
            parts.push(format!("{fname}: {code}"));
        }
        parts.join(", ")
    }

    fn resolve_record(&self, fields: &Record, expected: Option<&Ty>) -> String {
        if let Some(Ty::Record(name)) = expected {
            return name.clone();
        }
        let got: Vec<&str> = fields.iter().map(|(n, _, _)| n.as_str()).collect();
        self.records
            .iter()
            .find(|(name, defs)| {
                *name != MODEL
                    && defs.len() == got.len()
                    && defs.iter().all(|(n, _)| got.contains(&n.as_str()))
            })
            .map(|(name, _)| name.clone())
            .expect("typechecked: record literal resolves")
    }

    fn lookup(&self, name: &str, env: &Env) -> Ty {
        env.iter()
            .rev()
            .find(|(n, _)| n == name)
            .map(|(_, t)| t.clone())
            .expect("typechecked: var in scope")
    }

    /// Lightweight type inference for the places `emit` needs a type before
    /// emitting (list sources). Assumes a well-typed program.
    fn type_of(&self, expr: &Expr, env: &Env) -> Ty {
        match expr {
            Expr::Int(_) => Ty::Int,
            Expr::Str(_) => Ty::Str,
            Expr::Bool(_) => Ty::Bool,
            Expr::Var(name, _) => match env.iter().rev().find(|(n, _)| n == name) {
                Some((_, t)) => t.clone(),
                None => Ty::Enum(self.variant_owner[name].clone()),
            },
            Expr::Field(base, field, _) => match self.type_of(base, env) {
                Ty::Record(r) => self.field_ty(&r, field),
                _ => unreachable!(),
            },
            Expr::Show(..) => Ty::Str,
            Expr::Len(..) | Expr::Sum(..) | Expr::ToInt(..) => Ty::Int,
            Expr::Nth(list, _, _, _) => match self.type_of(list, env) {
                Ty::List(t) => *t,
                _ => unreachable!(),
            },
            Expr::Head(list, _) => match self.type_of(list, env) {
                Ty::List(t) => Ty::Maybe(t),
                _ => unreachable!(),
            },
            Expr::None(_) => Ty::Maybe(Box::new(Ty::Int)),
            Expr::Some(inner, _) => Ty::Maybe(Box::new(self.type_of(inner, env))),
            Expr::Case { arms, .. } => self.type_of(&arms[0].body, env),
            Expr::Ctor(name, _, _) => Ty::Enum(self.variant_owner[name].clone()),
            Expr::Reverse(inner, _) => self.type_of(inner, env),
            Expr::Not(..) => Ty::Bool,
            Expr::Bin(op, l, _, _) => match op {
                Op::Add | Op::Sub | Op::Mul => Ty::Int,
                Op::Concat => self.type_of(l, env),
                _ => Ty::Bool,
            },
            Expr::If(_, t, _, _) => self.type_of(t, env),
            Expr::ListLit(items, _) => {
                let elem = items
                    .first()
                    .map(|e| self.type_of(e, env))
                    .unwrap_or(Ty::Int);
                Ty::List(Box::new(elem))
            }
            Expr::RecordLit(fields, _) => Ty::Record(self.resolve_record(fields, None)),
            Expr::RecordUpdate(base, _, _) => self.type_of(base, env),
            Expr::For {
                var, list, body, ..
            } => {
                let elem = match self.type_of(list, env) {
                    Ty::List(t) => *t,
                    _ => unreachable!(),
                };
                let mut inner = env.clone();
                inner.push((var.clone(), elem));
                Ty::List(Box::new(self.type_of(body, &inner)))
            }
        }
    }
}

fn rust_ty(ty: &Ty) -> String {
    match ty {
        Ty::Int => "i64".into(),
        Ty::Str => "String".into(),
        Ty::Bool => "bool".into(),
        Ty::List(t) => format!("Vec<{}>", rust_ty(t)),
        Ty::Maybe(t) => format!("Option<{}>", rust_ty(t)),
        Ty::Enum(n) => n.clone(),
        Ty::Record(n) => n.clone(),
    }
}

/// A place expression cloned into an owned value when the type isn't Copy.
fn clone_if_owned(place: &str, ty: &Ty) -> String {
    match ty {
        Ty::Int | Ty::Bool => place.to_string(),
        _ => format!("{place}.clone()"),
    }
}

fn esc(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
}
