//! Backend v0: emit a Rust crate that plays the zumar TEA runtime directly.
//! The generated crate is indistinguishable from a hand-written example —
//! same builders, same `zumar_app!` wrapper, same wire protocol. A WasmGC
//! backend replaces this module later without touching the frontend.

use crate::ast::*;

pub struct Generated {
    pub crate_name: String,
    pub cargo_toml: String,
    pub lib_rs: String,
}

/// `zumar_path` is the relative path from the generated crate to the zumar
/// repo root (for `zumar-core`/`zumar-runtime` path dependencies).
pub fn generate(app: &App, zumar_path: &str) -> Generated {
    let crate_name = app.name.to_lowercase();
    Generated {
        cargo_toml: cargo_toml(&crate_name, zumar_path),
        lib_rs: lib_rs(app),
        crate_name,
    }
}

fn cargo_toml(name: &str, zumar: &str) -> String {
    format!(
        r#"[package]
name = "{name}"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
zumar-core = {{ path = "{zumar}/crates/zumar-core" }}
zumar-runtime = {{ path = "{zumar}/crates/zumar-runtime" }}
wasm-bindgen = "0.2"

[workspace]
"#
    )
}

fn lib_rs(app: &App) -> String {
    let mut out = String::new();
    let w = &mut out;

    w.push_str("//! Generated by zuc (zumar-lang v0). Do not edit; edit the .zu source.\n\n");
    w.push_str("use wasm_bindgen::prelude::*;\n");
    w.push_str("use zumar_core::{el, text, VNode};\n");
    w.push_str("use zumar_runtime::{effects::Cmds, Program};\n\n");

    // Msg
    w.push_str("#[derive(Clone)]\npub enum Msg {\n");
    for (msg, _) in &app.msgs {
        w.push_str(&format!("    {msg},\n"));
    }
    w.push_str("}\n\n");

    // Model
    w.push_str("pub struct Model {\n");
    for (field, ty, _) in &app.model {
        w.push_str(&format!("    pub {field}: {},\n", rust_ty(*ty)));
    }
    w.push_str("}\n\n");

    // init
    w.push_str("fn init_model() -> Model {\n    Model {\n");
    for (field, expr, _) in &app.init {
        w.push_str(&format!(
            "        {field}: {},\n",
            rust_expr(expr, self_ty(app, field))
        ));
    }
    w.push_str("    }\n}\n\n");

    // update — record-update semantics: evaluate all new values against the
    // pre-update model, then assign.
    w.push_str("fn update(model: &mut Model, msg: Msg) -> Cmds<Msg> {\n    match msg {\n");
    for (msg, record, _) in &app.updates {
        w.push_str(&format!("        Msg::{msg} => {{\n"));
        for (field, expr, _) in record {
            w.push_str(&format!(
                "            let __new_{field}: {} = {};\n",
                rust_ty(self_ty(app, field).unwrap()),
                rust_expr(expr, self_ty(app, field))
            ));
        }
        for (field, _, _) in record {
            w.push_str(&format!("            model.{field} = __new_{field};\n"));
        }
        w.push_str("        }\n");
    }
    w.push_str("    }\n    Vec::new()\n}\n\n");

    // view
    w.push_str("#[allow(unused_variables)]\nfn view(model: &Model) -> VNode<Msg> {\n    ");
    w.push_str(&rust_element(&app.view, 1));
    w.push_str("\n        .into()\n}\n\n");

    w.push_str(
        "zumar_runtime::zumar_app!(App, Model, Msg, Program::new(init_model(), update, view));\n",
    );
    out
}

fn self_ty(app: &App, field: &str) -> Option<Ty> {
    app.model
        .iter()
        .find(|(n, _, _)| n == field)
        .map(|(_, t, _)| *t)
}

fn rust_ty(ty: Ty) -> &'static str {
    match ty {
        Ty::Int => "i64",
        Ty::Str => "String",
        Ty::Bool => "bool",
    }
}

fn escape(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
}

/// Emit an expression. `ty` is the checked type (post-typecheck it always
/// resolves); String-typed expressions evaluate to owned `String`s.
fn rust_expr(expr: &Expr, ty: Option<Ty>) -> String {
    match expr {
        Expr::Int(n) => format!("{n}"),
        Expr::Bool(b) => format!("{b}"),
        Expr::Str(s) => format!("\"{}\".to_string()", escape(s)),
        Expr::Field(name, _) => match ty {
            Some(Ty::Str) => format!("model.{name}.clone()"),
            _ => format!("model.{name}"),
        },
        Expr::Show(inner, _) => format!("({}).to_string()", rust_expr(inner, Some(Ty::Int))),
        Expr::Bin(op, l, r, _) => match op {
            Op::Concat => format!(
                "format!(\"{{}}{{}}\", {}, {})",
                rust_expr(l, Some(Ty::Str)),
                rust_expr(r, Some(Ty::Str))
            ),
            Op::Add | Op::Sub | Op::Mul => format!(
                "({} {} {})",
                rust_expr(l, Some(Ty::Int)),
                match op {
                    Op::Add => "+",
                    Op::Sub => "-",
                    _ => "*",
                },
                rust_expr(r, Some(Ty::Int))
            ),
            Op::Eq | Op::Lt | Op::Gt => format!(
                "({} {} {})",
                rust_expr(l, None),
                match op {
                    Op::Eq => "==",
                    Op::Lt => "<",
                    _ => ">",
                },
                rust_expr(r, None)
            ),
        },
        Expr::If(c, t, e, _) => format!(
            "(if {} {{ {} }} else {{ {} }})",
            rust_expr(c, Some(Ty::Bool)),
            rust_expr(t, ty),
            rust_expr(e, ty)
        ),
    }
}

fn rust_element(el: &Element, depth: usize) -> String {
    let pad = "    ".repeat(depth + 1);
    let mut s = format!("el(\"{}\")", escape(&el.tag));
    for attr in &el.attrs {
        match attr {
            Attr::Str { name, value, .. } => {
                s.push_str(&format!(
                    "\n{pad}.attr(\"{}\", {})",
                    escape(name),
                    rust_expr(value, Some(Ty::Str))
                ));
            }
            Attr::OnClick { msg, .. } => {
                s.push_str(&format!("\n{pad}.on(\"click\", Msg::{msg})"));
            }
        }
    }
    for child in &el.children {
        match child {
            Child::Text(expr, _) => {
                s.push_str(&format!(
                    "\n{pad}.child(text({}))",
                    rust_expr(expr, Some(Ty::Str))
                ));
            }
            Child::Elem(e) => {
                s.push_str(&format!("\n{pad}.child({})", rust_element(e, depth + 1)));
            }
        }
    }
    s
}
